--extractor-args "youtube:player_client=web"
--embed-thumbnail
-f bestvideo[aspect_ratio<1][width<=1080][vcodec^=avc][ext=mp4]+bestaudio/bestvideo[aspect_ratio>=1][height<=1080][vcodec^=avc][ext=mp4]+bestaudio/bestvideo+bestaudio/best
