background_opacity          0.6
cursor_trail                1
window_padding_width        25
shell                       /usr/bin/zsh

include themes/noctalia.conf

map ctrl+c        copy_to_clipboard
map ctrl+v        paste_from_clipboard
map ctrl+shift+c  send_text all \x03
map ctrl+f        search_scrollback
