color0 #43483f
color1 #ffb4ab
color2 #a6d394
color3 #bbcbb1
color4 #a0cfd1
color5 #a6d394
color6 #bbcbb1
color7 #e1e4da
color8 #8d9387
color9 #ffb4ab
color10 #a6d394
color11 #bbcbb1
color12 #a0cfd1
color13 #a6d394
color14 #bbcbb1
color15 #e1e4da

cursor                #e1e4da
cursor_text_color     #11140f
background            #11140f
foreground            #e1e4da
selection_foreground  #c3c8bc
selection_background  #43483f
active_border_color   #a6d394
inactive_border_color #43483f
url_color             #a6d394

active_tab_foreground   #13380a
active_tab_background   #a6d394
inactive_tab_foreground #c3c8bc
inactive_tab_background #43483f
cursor_trail_color      #c3c8bc
